language: python
sudo: false

python:
  - "3.5"

env:
  - PYTHONPATH=$PYTHONPATH:$PWD

install:
  - pip install -r setup/requirements.txt
  - pip install -r setup/dev-requirements.txt

script:
  - py.test --verbose --cov=prince tests/
